name: "Test"

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Wiz
      uses: ChanTsune/setup-wiz@main

    - name: Run test
      run: wiz test
